- name: Configure control node
  hosts: "{{ var_hosts | default('control') }}"

- include: plays/ansibleruser.yml
  vars:
    var_hosts: control

- include: plays/control-install.yml
  vars:
    var_hosts: control

- include: plays/control-apache.yml
  vars:
    var_hosts: control
