- name: Configure python virtualenv and install services
  hosts: "{{ var_hosts | default('webheads') }}"
  vars_files:
  - vars/secrets.yml
  - vars/conf.yml

  tasks:
    - name: install git
      yum:
        name: git
        state: latest

    - name: install easy_install
      yum:
        name: python-setuptools
        state: latest

    - name: checkout broker
      git:
        repo: "https://{{ lookup('env', 'GIT_USER') | urlencode }}:{{ lookup('env', 'GIT_API_KEY') }}@github.com/mozilla/broker.git"
        dest: "{{ brokerdest }}"

    - name: checkout the mx service
      git:
        repo: "https://github.com/thundernest/http-mx.git"
        dest: "{{ mxdest }}"

    - name: delete live directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ live_doc_root }}"
        - "{{ autoconfig_trunk }}"

    - name: checkout the live redirects
      git:
        repo: "https://github.com/thundernest/live-redirects.git"
        dest: "{{ live_doc_root }}"

    - name: checkout autoconfig
      git:
        repo: "https://github.com/thundernest/autoconfig.git"
        dest: "{{ autoconfig_trunk }}"

    - name: install pip
      easy_install:
        name: pip
        state: latest

    - name: install virtualenv
      pip:
        name: virtualenv

    - name: install webob lib
      pip:
        name: webob
        virtualenv: "{{ services_virtualenv }}"
        virtualenv_python: python2.7

    - name: install mx requirements
      pip:
        requirements: "{{ mxdest }}/requirements.txt"
        virtualenv: "{{ services_virtualenv }}"
        virtualenv_python: python2.7

    - name: install packages for lxml compilation
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - "gcc"
        - "python-devel"
        - "libxml2"
        - "libxml2-devel"
        - "libxslt-devel"
        - "wget"

    - name: install lxml 2.2.3
      pip: name=lxml version=2.2.3 state=present virtualenv=/var/www/tbservices

    - name: copy autoconfig shell file
      copy:
        src: files/update.sh
        dest: /var/www/autoconfig.momo
        mode: 0744

    - name: run autoconfig shell file
      command: "/var/www/autoconfig.momo/update.sh"

    - name: set up autoconfig cron
      cron:
        name: "run autoconfig convert"
        minute: "30"
        user: "root"
        job: "/var/www/autoconfig.momo/update.sh"
