- name: Configure firewall and install Apache2
  hosts: "{{ var_hosts | default('webheads') }}"
  vars_files:
  - vars/conf.yml
  - vars/apache.yml

  pre_tasks:
    - name: Make Document Root
      file: path="{{ live_doc_root }}" state=directory

    - name: Make httpd dir
      file: path="/etc/httpd/conf/" state=directory

    - name: Make autoconfig log dir
      file: path="/var/log/httpd/autoconfig" state=directory

    - name: copy ssl certs
      copy:
        src: "{{ item }}"
        dest: /etc/httpd/conf
        mode: 0600
      with_items:
        - "files/privkey.pem"
        - "files/chain.pem"
        - "files/cert.pem"

    - name: install mod_wsgi
      yum:
        name: mod_wsgi
        state: latest

  roles:
    - { role: geerlingguy.apache }
