- name: Install broker
  hosts: "{{ var_hosts | default('webheads') }}"
  vars_files:
  - ../vars/conf.yml

  tasks:
  - name: checkout broker
    git:
      repo: "https://github.com/thundernest/broker.git"
      dest: "{{ brokerdest }}"
      version: "{{ branch | default('prod') }}"
