- name: Copy stats json files to web servers.
  hosts: webheads
  vars:
    stats_dest: "/var/www/html/tbstats/docs"

  tasks:
    - name: Copy all json data.
      copy:
        src: "{{ item }}"
        dest: "{{ stats_dest }}"
        owner: root
        group: root
        mode: 0755
      with_fileglob:
        - ~/stats/docs/*.json
